export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const COMPLETED_REGISTRATION = 'COMPLETED_REGISTRATION';

export const SET_IS_MAIN_USER = 'SET_IS_MAIN_USER';

export const ADD_NEW_POST_START = 'ADD_NEW_POST_START';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const EDIT_USER_DATA_START = 'EDIT_USER_DATA_START';
export const EDIT_USER_DATA_SUCCESS = 'EDIT_USER_DATA_SUCCESS';
export const EDIT_USER_DATA_FAIL = 'EDIT_USER_DATA_FAIL';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_EMPTY = 'FETCH_POSTS_EMPTY';
export const RESET_FEED = 'RESET_FEED';

export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';

export const FETCH_USER_POSTS_START = 'FETCH_USER_POSTS_START';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAIL = 'FETCH_USER_POSTS_FAIL';
export const FETCH_USER_POSTS_EMPTY = 'FETCH_USER_POSTS_EMPTY';
export const RESET_USER_FEED = 'RESET_USER_FEED';

export const TOGGLE_LIKE_START = 'TOGGLE_LIKE_START';
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS';
export const TOGGLE_LIKE_FAIL = 'TOGGLE_LIKE_FAIL';

export const SEARCH_USERS_START = 'SEARCH_USERS_START';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
export const SEARCH_USERS_EMPTY = 'SEARCH_USERS_EMPTY';

export const TOGGLE_FOLLOW_USER_START = 'TOGGLE_FOLLOW_USER_START';
export const TOGGLE_FOLLOW_USER_SUCCESS = 'TOGGLE_FOLLOW_USER_SUCCESS';
export const TOGGLE_FOLLOW_USER_FAIL = 'TOGGLE_FOLLOW_USER_FAIL';
export const FETCH_FROM_FEED = 'FETCH_FROM_FEED';

export const FETCH_USER_FOLLOWING_ARR = 'FETCH_USER_FOLLOWING_ARR';

export const RESET_REDIRECT = 'RESET_REDIRECT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

